import 'package:flutter_fuerza_natural_login/core/models/finca_model.dart';
import 'package:flutter_fuerza_natural_login/core/models/reserva_model.dart';
import 'package:flutter_fuerza_natural_login/core/models/user_model.dart';

class MockDataService {
  // ── Current logged-in user ─────────────────────────────────────────────────
  static UserModel get currentUser => UserModel(
        id: 'u1',
        nombre: 'Carlos',
        apellidos: 'Rodríguez',
        email: 'carlos.rodriguez@email.com',
        telefono: '+34 612 345 678',
        ubicacion: 'Madrid, España',
        fechaRegistro: DateTime(2022, 3, 15),
        reservasRealizadas: 12,
        fincasCount: 1,
        rol: UserRole.cliente,
      );

  // ── All available fincas ──────────────────────────────────────────────────
  static List<FincaModel> get fincasDisponibles => [
        FincaModel(
          id: 'f1',
          nombre: 'El Robledal',
          descripcion:
              'Finca de caza mayor en plena Sierra de Gredos. Terreno montañoso con abundante vegetación. Ideal para la caza de ciervo y jabalí.',
          provincia: 'Ávila',
          pais: 'España',
          localidad: 'Sierra de Gredos',
          superficie: 850,
          precioDia: 350,
          valoracion: 4.8,
          numeroResenas: 24,
          especies: ['Ciervo', 'Jabalí', 'Corzo'],
          servicios: ['Alojamiento', 'Guía de caza', 'Comidas incluidas'],
          normas: [
            'Licencia de caza obligatoria',
            'No disparar desde vehículos',
            'Respetar todos los acotados',
          ],
          destacada: true,
          estado: EstadoFinca.activa,
          propietarioId: 'owner1',
          totalReservas: 48,
          reservasPendientes: 3,
        ),
        FincaModel(
          id: 'f2',
          nombre: 'Sierra Alta',
          descripcion:
              'Privilegiada finca de caza en los montes de León. Variedad de terrenos, desde praderas hasta bosques de encina y roble.',
          provincia: 'León',
          pais: 'España',
          localidad: 'Montes de León',
          superficie: 1200,
          precioDia: 420,
          valoracion: 4.6,
          numeroResenas: 18,
          especies: ['Ciervo', 'Jabalí', 'Gamo', 'Corzo'],
          servicios: ['Alojamiento', 'Transporte', 'Guía de caza'],
          normas: [
            'Se requiere licencia nacional',
            'Máximo 8 cazadores por jornada',
            'Prohibido cazar en zonas señalizadas',
          ],
          destacada: true,
          estado: EstadoFinca.activa,
          propietarioId: 'owner2',
          totalReservas: 32,
          reservasPendientes: 1,
        ),
        FincaModel(
          id: 'f3',
          nombre: 'Los Encinas',
          descripcion:
              'Finca de caza menor en La Mancha. Terreno llano con encinas y manchas de matorral. Abundante perdiz roja y codorniz.',
          provincia: 'Ciudad Real',
          pais: 'España',
          localidad: 'La Mancha',
          superficie: 400,
          precioDia: 180,
          valoracion: 4.3,
          numeroResenas: 31,
          especies: ['Perdiz', 'Codorniz', 'Conejo', 'Liebre'],
          servicios: ['Guía de caza', 'Perros de caza'],
          normas: [
            'Caza menor únicamente',
            'Prohibido uso de rehala sin autorización',
          ],
          destacada: false,
          estado: EstadoFinca.activa,
          propietarioId: 'owner3',
          totalReservas: 67,
          reservasPendientes: 0,
        ),
        FincaModel(
          id: 'f4',
          nombre: 'Monte Verde Premium',
          descripcion:
              'Exclusiva finca premium en Extremadura. Dehesa centenaria con acebuches y alcornoques. La mejor experiencia de caza de ciervo.',
          provincia: 'Cáceres',
          pais: 'España',
          localidad: 'Dehesa de Cáceres',
          superficie: 2000,
          precioDia: 600,
          valoracion: 4.9,
          numeroResenas: 12,
          especies: ['Ciervo', 'Gamo', 'Muflón', 'Jabalí'],
          servicios: [
            'Alojamiento',
            'Comidas incluidas',
            'Transporte',
            'Guía de caza',
            'Fotografía',
          ],
          normas: [
            'Reserva mínima de 2 días',
            'Experiencia de caza requerida',
            'Equipamiento propio obligatorio',
          ],
          destacada: false,
          estado: EstadoFinca.activa,
          propietarioId: 'owner4',
          totalReservas: 19,
          reservasPendientes: 2,
        ),
      ];

  static List<FincaModel> get fincasDestacadas =>
      fincasDisponibles.where((f) => f.destacada).toList();

  // ── Owner's fincas ────────────────────────────────────────────────────────
  static List<FincaModel> get misFincas => [
        FincaModel(
          id: 'mf1',
          nombre: 'Finca Los Olivos',
          descripcion:
              'Mi finca de caza en la Sierra de Guadarrama. Ideal para ciervo y jabalí.',
          provincia: 'Madrid',
          pais: 'España',
          localidad: 'Sierra de Guadarrama',
          superficie: 650,
          precioDia: 300,
          valoracion: 4.5,
          numeroResenas: 8,
          especies: ['Ciervo', 'Jabalí', 'Corzo'],
          servicios: ['Alojamiento', 'Guía de caza'],
          normas: ['Licencia obligatoria', 'Máximo 6 cazadores'],
          destacada: false,
          estado: EstadoFinca.activa,
          propietarioId: 'u1',
          totalReservas: 8,
          reservasPendientes: 2,
        ),
      ];

  // ── User's reservations ───────────────────────────────────────────────────
  static List<ReservaModel> get misReservas => [
        ReservaModel(
          id: 'r1',
          clienteId: 'u1',
          clienteNombre: 'Carlos Rodríguez',
          fincaId: 'f1',
          fincaNombre: 'El Robledal',
          fincaProvincia: 'Ávila',
          fincaPais: 'España',
          fincaImageUrl: '',
          fechaInicio: DateTime.now().add(const Duration(days: 15)),
          fechaFin: DateTime.now().add(const Duration(days: 17)),
          numeroDias: 2,
          numeroPersonas: 4,
          estado: EstadoReserva.confirmada,
          precioTotal: 1050,
          fechaReserva: DateTime.now().subtract(const Duration(days: 5)),
        ),
        ReservaModel(
          id: 'r2',
          clienteId: 'u1',
          clienteNombre: 'Carlos Rodríguez',
          fincaId: 'f2',
          fincaNombre: 'Sierra Alta',
          fincaProvincia: 'León',
          fincaPais: 'España',
          fincaImageUrl: '',
          fechaInicio: DateTime.now().add(const Duration(days: 30)),
          fechaFin: DateTime.now().add(const Duration(days: 32)),
          numeroDias: 2,
          numeroPersonas: 6,
          estado: EstadoReserva.pendiente,
          precioTotal: 1260,
          fechaReserva: DateTime.now().subtract(const Duration(days: 1)),
        ),
        ReservaModel(
          id: 'r3',
          clienteId: 'u1',
          clienteNombre: 'Carlos Rodríguez',
          fincaId: 'f3',
          fincaNombre: 'Los Encinas',
          fincaProvincia: 'Ciudad Real',
          fincaPais: 'España',
          fincaImageUrl: '',
          fechaInicio: DateTime.now().subtract(const Duration(days: 30)),
          fechaFin: DateTime.now().subtract(const Duration(days: 28)),
          numeroDias: 2,
          numeroPersonas: 3,
          estado: EstadoReserva.completada,
          precioTotal: 540,
          fechaReserva: DateTime.now().subtract(const Duration(days: 40)),
        ),
        ReservaModel(
          id: 'r4',
          clienteId: 'u1',
          clienteNombre: 'Carlos Rodríguez',
          fincaId: 'f4',
          fincaNombre: 'Monte Verde Premium',
          fincaProvincia: 'Cáceres',
          fincaPais: 'España',
          fincaImageUrl: '',
          fechaInicio: DateTime.now().subtract(const Duration(days: 90)),
          fechaFin: DateTime.now().subtract(const Duration(days: 88)),
          numeroDias: 2,
          numeroPersonas: 5,
          estado: EstadoReserva.completada,
          precioTotal: 3000,
          fechaReserva: DateTime.now().subtract(const Duration(days: 100)),
        ),
      ];

  // ── Spanish provinces ─────────────────────────────────────────────────────
  static const List<String> provincias = [
    'Álava',
    'Albacete',
    'Alicante',
    'Almería',
    'Asturias',
    'Ávila',
    'Badajoz',
    'Barcelona',
    'Burgos',
    'Cáceres',
    'Cádiz',
    'Cantabria',
    'Castellón',
    'Ciudad Real',
    'Córdoba',
    'A Coruña',
    'Cuenca',
    'Girona',
    'Granada',
    'Guadalajara',
    'Guipúzcoa',
    'Huelva',
    'Huesca',
    'Islas Baleares',
    'Jaén',
    'León',
    'Lleida',
    'Lugo',
    'Madrid',
    'Málaga',
    'Murcia',
    'Navarra',
    'Ourense',
    'Palencia',
    'Las Palmas',
    'Pontevedra',
    'La Rioja',
    'Salamanca',
    'Segovia',
    'Sevilla',
    'Soria',
    'Tarragona',
    'Santa Cruz de Tenerife',
    'Teruel',
    'Toledo',
    'Valencia',
    'Valladolid',
    'Vizcaya',
    'Zamora',
    'Zaragoza',
  ];
}
